---
title: "ICD Table Analysis"
author: "Cindy Kartman"
date: "March 5, 2017"
output: word_document
---


```{r}
########Find Hep C patients from icd diagnosis codes

##Match icd 9 codes per Dr Davis's email
hep_c_icd_dx <- subset(diagnosis_icd, 
                        icd_dx == "V02.62" | #Carrier or suspected carrier of Hep C (icd9)
                        icd_dx == "Z22.52" | #Carrier or suspected carrier of Hep C (icd10)
                        icd_dx == "V12.09" | #Hepatitis C, history of (icd9)
                        #icd_dx == "070.41" | #Acute hepatitis C with hepatic coma (icd9)
                        #icd_dx == "070.44" | #Chronic hepatitis C with hepatic coma (icd9)
                        #icd_dx == "070.51" | #Acute hepatitis C without mention of hepatic coma (icd9)
                        icd_dx == "070.54" | #Chronic hepatitis C without mention of hepatic coma; reat that it can be used as hep c in remission (icd9)
                        #icd_dx == "070.7" | #Unspecified viral hepatitis C (icd9)
                        icd_dx == "070.70" | #Unspecified viral hepatitis C without hepatic coma (icd9)
                        icd_dx == "070.71" | #Unspecified viral hepatitis C with hepatic coma (icd9)
                        icd_dx == "B19.20" | #Unspecified viral hepatitis C without hepatic coma (icd10)
                        icd_dx == "B1920" | #Unspecified viral hepatitis C without hepatic coma (icd10)
                        icd_dx == "B18.2" | #Chronic viral hep C (icd10)
                        #icd_dx == "B1710" | #Acute hepatitis C without hepatic coma (icd10)
                        icd_dx == "B19.21" | #Unspecified viral hepatitis C with hepatic coma (icd10)
                        icd_dx == "B1921"  #Unspecified viral hepatitis C with hepatic coma (icd10)
)

#Codes below were not included - These are icd 10 codes - there doesn't seem to be specific Hep C codes during pregnancy for icd 9
#"O98411" (icd10) - Viral hepatitis complicating pregnancy, first trimester
#"O98412" (icd10) - Viral hepatitis complicating pregnancy, second trimester
#"O9842" (icd10) - "VIRAL HEPATITIS COMPLICATING CHILDBIRTH"  
#"O98413" (icd10) - "VIRAL HEPATITIS COMP PREGNANCY THIRD TRIMESTER" 

dim(hep_c_icd_dx)#26540
table(hep_c_icd_dx$icd_dx)
table(hep_c_icd_dx$icd_diagnosis)


length(unique(hep_c_icd_dx$PATIENT_ID)) #3768 unique patient id's #3707

#Barplot
hep_c_icd_dx_graph <- barplot(table(hep_c_icd_dx$icd_dx), 
                                 xlab = "ICD Code", ylab = "Frequency", main = "# of Times ICD Code Appears in ICD Table",
                                 ylim = c(0, 20000))
text(hep_c_icd_dx_graph, table(hep_c_icd_dx$icd_diagnosis), labels = table(hep_c_icd_dx$icd_diagnosis), pos = 3)

#####Find first hep c diagnosis dates#######

#Create an object with id numbers of unique patients with a Hep C icd code and the date of that first diagnosis date
#####

#find earilest hep C icd code using aggregate 
hep_c_patients_ids_first_hep_c_encounter_date <- aggregate(enc_dt_ds~PATIENT_ID,  data = hep_c_icd_dx, min) 

#rename encounter date column
names(hep_c_patients_ids_first_hep_c_encounter_date)[names(hep_c_patients_ids_first_hep_c_encounter_date) == "enc_dt_ds"] <- "First_Date_with_Hep_C_ICD_code"

str(hep_c_patients_ids_first_hep_c_encounter_date)
dim(hep_c_patients_ids_first_hep_c_encounter_date)
length(unique(hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID))




```
```{r}
##Finding first encounter date for Hep C patients
#Filter encounter table on Hep C patients only
hep_c_patient_encounters <- encounters[encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
names(hep_c_patient_encounters)

#reduce dataset to date and id field only
hep_c_patient_encounters_dates <- hep_c_patient_encounters[c("PATIENT_ID", "ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "Enc_DT_DS", "Appt_DTTM_DS", "Appt_Checkin_DTTM", "Appt_Cancel_DTTM_DS", "ED_Arrival_DTTM_DS", "Hsp_Adm_DTTM_DS", "Hsp_Disch_DTTM_DS")]
dim(hep_c_patient_encounters_dates)


#find min encounter datefor hep C patients; change column name 
hep_c_patients_first_encounter_date <- aggregate(Enc_DT_DS~PATIENT_ID,  data = hep_c_patient_encounters_dates, min)
names(hep_c_patients_first_encounter_date)[names(hep_c_patients_first_encounter_date) == "Enc_DT_DS"] <- "First_Encounter_Date"
str(hep_c_patients_ids_first_hep_c_encounter_date)

#merge encounter dates with first hep c diangosis date
hep_c_patients_first_encounter_date_and_first_hep_c_icd_code <- merge(hep_c_patients_first_encounter_date, hep_c_patients_ids_first_hep_c_encounter_date, by ="PATIENT_ID")
str(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code)

#Evaluate whether first enounter date is greater, less or equal to first encounter date
hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$EncountervsICD <- ifelse(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$First_Encounter_Date < hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$First_Date_with_Hep_C_ICD_code,  "TRUE", "FALSE")

nrow(subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == 'TRUE'))
nrow(subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == 'FALSE'))

#save listings of ID's with date of first diagnosis 
write.csv(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, "Z:/hep_c_patients_first_encounter_date_and_first_hep_c_icd_code.csv")


```

```{r}

############# DIAGNOSIS ICD Table #############


#exploring number of unique values, what the unique values are, # of rows with values it and the # of rows with NA's
icd_9 <- (subset(diagnosis_icd, ICD_TYPE == 9)) #icd 9 codes = 8,016,285 rows 
icd_10 <- (subset(diagnosis_icd, ICD_TYPE == 10)) #icd 10 codes = 520,609 rows
length(unique(icd_9$icd_dx)) #10593 unique icd codes
length(unique(icd_10$icd_dx)) #9837 unique icd codes


####Number of 
#Hep C Patients - Number of diagnosis_icd codes and Average number of diagnosis_icd codes per patient
hep_c_patient_diagnosis_icd <- diagnosis_icd[diagnosis_icd$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_diagnosis_icd)
nrow(hep_c_patient_diagnosis_icd) / nrow(diagnosis_icd)
nrow(hep_c_patient_diagnosis_icd)/length(unique(hep_c_patient_diagnosis_icd$PATIENT_ID))

##Frequency of ICD Diagnosis codes
#all records
hep_c_icd_code_freq<- (as.data.frame(table(hep_c_patient_diagnosis_icd$icd_diagnosis)))
head(hep_c_icd_code_freq[order(-hep_c_icd_code_freq$Freq),], n=10)

#unduplicated
unique_hep_c_patient_diagnosis_icd <-hep_c_patient_diagnosis_icd[!duplicated(hep_c_patient_diagnosis_icd),]
hep_c_icd_code_freq<- (as.data.frame(table(hep_c_patient_diagnosis_icd$icd_diagnosis)))
head(hep_c_icd_code_freq[order(-hep_c_icd_code_freq$Freq),], n=10)


#Non Hep C Patients - Number of diagnosis_icd and Average number of diagnosis_icd per patient
non_hep_c_patient_diagnosis_icd <- diagnosis_icd[!diagnosis_icd$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_diagnosis_icd)
nrow(non_hep_c_patient_diagnosis_icd) / nrow(diagnosis_icd)
nrow(non_hep_c_patient_diagnosis_icd)/length(unique(non_hep_c_patient_diagnosis_icd$PATIENT_ID))

##Frequency of ICD Diagnosis codes
#all records
non_hep_c_icd_code_freq<- (as.data.frame(table(non_hep_c_patient_diagnosis_icd$icd_diagnosis)))
head(non_hep_c_icd_code_freq[order(-non_hep_c_icd_code_freq$Freq),], n=10)




#####number of hep c diagnosis codes per unique patient #####
num_of_hep_c_codes_per_patient <- as.data.frame(aggregate(ENCOUNTER_ID~PATIENT_ID, data = hep_c_icd_dx, FUN = length))
colnames(num_of_hep_c_codes_per_patient) <- c("PATIENT_ID", "Total_Num_of_Hep_C_codes")

head(num_of_hep_c_codes_per_patient[order(-num_of_hep_c_codes_per_patient$Total_Num_of_Hep_C_codes),])#sort with most hep_c_codes on top

nrow(subset(num_of_hep_c_codes_per_patient, Total_Num_of_Hep_C_codes == 1)) #1295 unique patients with 1 hep c diagnosis code 1288
nrow(subset(num_of_hep_c_codes_per_patient, Total_Num_of_Hep_C_codes >= 5)) #1551 unique patients with 5 or greater hep c diagnosis code #1492
```




```{r}
###################Unique Patient ID Dataset - Analyzing what we have on patients############

patient_ID_encounters <- as.data.frame(table(encounters$PATIENT_ID))
colnames(patient_ID_encounters) <- c("PATIENT_ID", "Count_Encounters")

patient_ID_diagnosis_icd <- as.data.frame(table(diagnosis_icd$PATIENT_ID))
colnames(patient_ID_diagnosis_icd) <- c("PATIENT_ID", "Count_Diagnosis_ICD")

merge_1 <- merge(patient_ID_encounters, patient_ID_diagnosis_icd, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)
sum(is.na(merge_1))

patient_ID_cpt <- as.data.frame(table(cpt$PATIENT_ID))
colnames(patient_ID_cpt) <- c("PATIENT_ID", "Count_CPT")

merge_2 <- merge(merge_1, patient_ID_cpt, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_med_rec_adm <- as.data.frame(table(med_rec_adm$PATIENT_ID))
colnames(patient_ID_med_rec_adm) <- c("PATIENT_ID", "Count_Med_Rec_ADM")

merge_3 <- merge(merge_2, patient_ID_med_rec_adm, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_med_rec_dc <- as.data.frame(table(med_rec_dc$PATIENT_ID))
colnames(patient_ID_med_rec_dc) <- c("PATIENT_ID", "Count_Med_Rec_DC")

merge_4 <- merge(merge_3, patient_ID_med_rec_dc, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_meds_inpt <- as.data.frame(table(meds_inpt$PATIENT_ID))
colnames(patient_ID_meds_inpt) <- c("PATIENT_ID", "Count_Meds_Inpt")

merge_5 <- merge(merge_4, patient_ID_meds_inpt, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_meds_outpt <- as.data.frame(table(meds_outpt$PATIENT_ID))
colnames(patient_ID_meds_outpt) <- c("PATIENT_ID", "Count_Meds_Outpt")

merge_6 <- merge(merge_5, patient_ID_meds_outpt, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_procedure_icd <- as.data.frame(table(procedure_icd$PATIENT_ID))
colnames(patient_ID_procedure_icd) <- c("PATIENT_ID", "Count_Procedure_ICD")

merge_7 <- merge(merge_6, patient_ID_procedure_icd, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_social <- as.data.frame(table(social_hx$PATIENT_ID))
colnames(patient_ID_social) <- c("PATIENT_ID", "Count_Social")

merge_8 <- merge(merge_7, patient_ID_social, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_demo <- as.data.frame(table(demo$PATIENT_ID))
colnames(patient_ID_demo) <- c("PATIENT_ID", "Count_Demo")

merge_9 <- merge(merge_8, patient_ID_demo, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

patient_ID_labs <- as.data.frame(table(labs$PATIENT_ID))
colnames(patient_ID_labs) <- c("PATIENT_ID", "Count_labs")

merge_10 <- merge(merge_9, patient_ID_labs, by = "PATIENT_ID", all.x = TRUE, all.y = TRUE)

write.csv(merge_10, "Z:/Hepatitis C Project/patient_ID_freq.csv")

#Filter out patients with a Hep C icd diagnosis
#import hep c patient ID listing
unique_hep_c_patient_ids<-read.csv("Z:/unique_hep_c_patient_ids.csv", header = TRUE)#Cindy's data path
str(unique_hep_c_patient_ids)

#filter merge_10 so only hep C patients are shown
unique_hep_c_patients_freq <- subset(merge_10, PATIENT_ID %in% unique_hep_c_patient_ids$PATIENT_ID) 

#Export to csv
write.csv(unique_hep_c_patients_freq, "Z:/unique_hep_c_patients_freq.csv")
```

```{r}
###################Unique Encounter ID Dataset - Analyzing what we have on encoutners############
encounter_ID_encounters <- as.data.frame(table(encounters$ENCOUNTER_ID))
colnames(encounter_ID_encounters) <- c("ENCOUNTER_ID", "Count_Encounters")

encounter_ID_diagnosis_icd <- as.data.frame(table(diagnosis_icd$ENCOUNTER_ID))
colnames(encounter_ID_diagnosis_icd) <- c("ENCOUNTER_ID", "Count_Diagnosis_ICD")

merge_1.2 <- merge(encounter_ID_encounters, encounter_ID_diagnosis_icd, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_cpt <- as.data.frame(table(cpt$ENCOUNTER_ID))
colnames(encounter_ID_cpt) <- c("ENCOUNTER_ID", "Count_CPT")

merge_2.2 <- merge(merge_1.2, encounter_ID_cpt, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_med_rec_adm <- as.data.frame(table(med_rec_adm$ENCOUNTER_ID))
colnames(encounter_ID_med_rec_adm) <- c("ENCOUNTER_ID", "Count_Med_Rec_ADM")

merge_3.2 <- merge(merge_2.2, encounter_ID_med_rec_adm, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_med_rec_dc <- as.data.frame(table(med_rec_dc$ENCOUNTER_ID))
colnames(encounter_ID_med_rec_dc) <- c("ENCOUNTER_ID", "Count_Med_Rec_DC")

merge_4.2 <- merge(merge_3.2, encounter_ID_med_rec_dc, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_meds_inpt <- as.data.frame(table(meds_inpt$ENCOUNTER_ID))
colnames(encounter_ID_meds_inpt) <- c("ENCOUNTER_ID", "Count_Meds_Inpt")

merge_5.2 <- merge(merge_4.2, encounter_ID_meds_inpt, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_meds_outpt <- as.data.frame(table(meds_outpt$ENCOUNTER_ID))
colnames(encounter_ID_meds_outpt) <- c("ENCOUNTER_ID", "Count_Meds_Outpt")

merge_6.2 <- merge(merge_5.2, encounter_ID_meds_outpt, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_procedure_icd <- as.data.frame(table(procedure_icd$ENCOUNTER_ID))
colnames(encounter_ID_procedure_icd) <- c("ENCOUNTER_ID", "Count_Procedure_ICD")

merge_7.2 <- merge(merge_6.2, encounter_ID_procedure_icd, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

encounter_ID_social <- as.data.frame(table(social_hx$ENCOUNTER_ID))
colnames(encounter_ID_social) <- c("ENCOUNTER_ID", "Count_Social")

merge_8.2 <- merge(merge_7.2, encounter_ID_social, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

#encounter_ID_labs <- as.data.frame(table(labs$ENCOUNTER_ID))
#colnames(encounter_ID_labs) <- c("ENCOUNTER_ID", "Count_labs")
#merge_9.2 <- merge(merge_8.2, encounter_ID_demo, by = "ENCOUNTER_ID", all.x = TRUE, all.y = TRUE)

write.csv(merge_8.2, "Z:/Hepatitis C Project/encounter_ID_freq.csv")
```



```{r}
####Exploring Encounter Table####


#Encounters for Hep C Patients and Non Hep C Patients

nrow(encounters)

#Hep C Patients - Number of Encounters and Average number of encounters per patient
hep_c_patient_encounters <- encounters[encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_encounters)
nrow(hep_c_patient_encounters) / nrow(encounters)
nrow(hep_c_patient_encounters)/length(unique(hep_c_patient_encounters$PATIENT_ID))
str(hep_c_patient_encounters)

#Non Hep C Patients - Number of Encounters and Average number of encounters per patient
non_hep_c_patient_encounters <- encounters[!encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_encounters)
nrow(non_hep_c_patient_encounters) / nrow(encounters)
nrow(non_hep_c_patient_encounters)/length(unique(non_hep_c_patient_encounters$PATIENT_ID))

### Look at encounter type and the percent of NA's in each type


sum(is.na(encounters$ENCOUNTER_ID))

sum(is.na(encounterS$Enc_DT_DS))

#___ NA in encounter ID out of ___ ROWS

unique(encounters$Enc_EIO)

####looking at observations by encounter EIO

#outpatient entcounter
outpatient_encounters <- encounters[(encounters$Enc_EIO %in% c("O", "I, O", "E, O", "E, I, O")),]

#Hep C Patients - Number of Outpatient Encounters and Average number of outpatient encounters per patient
hep_c_patient_outpatient_encounters <- outpatient_encounters [outpatient_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_outpatient_encounters)
nrow(hep_c_patient_outpatient_encounters) / nrow(outpatient_encounters)
nrow(hep_c_patient_outpatient_encounters)/length(unique(hep_c_patient_outpatient_encounters$PATIENT_ID))
str(hep_c_patient_outpatient_encounters)

#Non Hep C Patients - Number of Outpatient Encounters and Average number of outpatient encounters per patient
non_hep_c_patient_oupatient_encounters <- outpatient_encounters[!outpatient_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_oupatient_encounters)
nrow(non_hep_c_patient_oupatient_encounters) / nrow(outpatient_encounters)
nrow(non_hep_c_patient_oupatient_encounters)/length(unique(non_hep_c_patient_oupatient_encounters$PATIENT_ID))

sum(is.na(outpatient_encounters$ENCOUNTER_ID))


####ED Encounters
emergency_encounters <- encounters[(encounters$Enc_EIO %in% c("E", "E, I", "E, O", "E, I, O")),]
sum(is.na(emergency_encounters$ENCOUNTER_ID))

#Hep C Patients - Number of ED Encounters and Average number of EDencounters per patient
hep_c_patient_ed_encounters <- emergency_encounters [emergency_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_ed_encounters)
nrow(hep_c_patient_ed_encounters) / nrow(emergency_encounters)
nrow(hep_c_patient_ed_encounters)/length(unique(hep_c_patient_ed_encounters$PATIENT_ID))


#Non Hep C Patients - Number of ED Encounters and Average number of ED encounters per patient
non_hep_c_patient_ed_encounters <- emergency_encounters[!emergency_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_ed_encounters)
nrow(non_hep_c_patient_ed_encounters) / nrow(inpatient_encounters)
nrow(non_hep_c_patient_ed_encounters)/length(unique(non_hep_c_patient_ed_encounters$PATIENT_ID))

####Inpatient Encounters
inpatient_encounters <- encounters[(encounters$Enc_EIO %in% c("I, O", "I", "E, I", "E, I, O")),]
sum(is.na(inpatient_encounters$ENCOUNTER_ID))

#Hep C Patients - Number of inpatient Encounters and Average number of inpatient encounters per patient
hep_c_patient_inpatient_encounters <- inpatient_encounters [inpatient_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_inpatient_encounters)
nrow(hep_c_patient_inpatient_encounters) / nrow(inpatient_encounters)
nrow(hep_c_patient_inpatient_encounters)/length(unique(hep_c_patient_inpatient_encounters$PATIENT_ID))


#Non Hep C Patients - Number of inpatient Encounters and Average number of inpatient encounters per patient
non_hep_c_patient_inpatient_encounters <- inpatient_encounters[!inpatient_encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_inpatient_encounters)
nrow(non_hep_c_patient_inpatient_encounters) / nrow(inpatient_encounters)
nrow(non_hep_c_patient_inpatient_encounters)/length(unique(non_hep_c_patient_inpatient_encounters$PATIENT_ID))



#looking at obersations where the appointment type is = appointment and there is a NA for encounter ID

encounters[encounters$Encounter_Type == "Appointment" & is.na(encounters$ENCOUNTER_ID),]

#vector of unique types of encounter type
encounter_type <- unique(encounters$Encounter_Type)

#finding the total number of observations for each encounter type
encounter_type_freq <- sapply(encounter_type, function(x)
    sum(nrow(encounters[encounters$Encounter_Type == x,])))

##finding the total number of observations with NA for encounter ID for each type of encounter type
num_of_NA_by_encounter_type <- sapply(encounter_type, function(x)
    sum(nrow(encounters[encounters$Encounter_Type == x & 
                                            is.na(encounters$ENCOUNTER_ID) ,])))

#caculating the percent of NA's for each encounter type
Percent_of_NA <- round((num_of_NA_by_encounter_type / encounter_type_freq), 2)

#combining the 3 previous objects into a dataframe
encounter_type_and_ID_df <- as.data.frame(cbind(encounter_type_freq, num_of_NA_by_encounter_type, Percent_of_NA ))

encounter_type_and_ID_df[order(-encounter_type_and_ID_df$encounter_type_freq),]

write.csv(encounter_type_and_ID_df, "Z:/Cindy's Folder/encounter_type_and_ID_NA_freq_df.csv")



####Encounter Table
##Combine hep c patient ID listing to encounter table to get all encounters for hep c patients
hep_c_patient_encounters <- encounters[encounters$PATIENT_ID %in% unique_hep_c_ids$PATIENT_ID,]
dim(hep_c_patient_encounters)# 463,271rows
dim(hep_c_patients_first_hep_c_encounter_date)
    
#merge first hep c icd diagnosit date with encounters for hep c patients
hep_c_patient_encounters <- merge(hep_c_patients_first_hep_c_encounter_date, hep_c_patient_encounters, by ="PATIENT_ID")

#order by increasing patient ID and decreaseing encounter date
hep_c_patient_encounters <- hep_c_patient_encounters[order(hep_c_patient_encounters$PATIENT_ID, hep_c_patient_encounters$Enc_DT_DS),]

#creating new column to determine whether encounter date is before or after date of first hep c icd diagnosis code
hep_c_patient_encounters$Diagnosis_before_after_first_encounter <- ifelse(hep_c_patient_encounters$Enc_DT_DS > hep_c_patient_encounters$hep_c_patients_first_hep_c_encounter_date, "AFTER", "BEFORE")

#can filter on before and after -can do this for all tables to filter out rows before collasping at a patient level.
```

```{r}
#######  Look at cpt and icd procedure table ##########

head(procedure_icd)

head(cpt)

encounter_procedure_icd_merge <- merge(encounters, procedure_icd, by.x = "ENCOUNTER_ID", by.y = "encounter_id")
dim(encounter_procedure_icd_merge)
nrow(encounter_procedure_icd_merge[(encounter_procedure_icd_merge$Enc_EIO %in% c("I, O", "I", "E, I", "E, I, O")),])

encounter_cpt_merge <- merge(encounters, cpt, by.x = "ENCOUNTER_ID", by.y = "encounter_id")
dim(encounter_cpt_merge)
encounter_cpt_merge[(encounter_cpt_merge$Enc_EIO == "E, O"),]

encounter_cpt_merge[(encounter_cpt_merge$Enc_EIO %in% c("O", "I, O", "E, O", "E, I, O")),]
encounter_cpt_merge[(encounter_cpt_merge$Enc_EIO %in% c("I, O", "I", "E, I", "E, I, O")),]

#Hep C Patients - Number of procedures codes and Average number of procedures codes per patient
hep_c_patient_cpt <- cpt[cpt$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(hep_c_patient_cpt)
nrow(hep_c_patient_cpt) / nrow(cpt)
nrow(hep_c_patient_cpt)/length(unique(hep_c_patient_cpt$PATIENT_ID))

##Frequency of CPT codes
#all records
hep_c_cpt_freq<- (as.data.frame(table(hep_c_patient_cpt$CPT)))
head(hep_c_cpt_freq[order(-hep_c_cpt_freq$Freq),], n=10)

#unduplicated

#unique_hep_c_patient_diagnosis_icd <-hep_c_patient_diagnosis_icd[!duplicated(hep_c_patient_diagnosis_icd),]
#hep_c_icd_code_freq<- (as.data.frame(table(hep_c_patient_diagnosis_icd$icd_diagnosis)))
#head(hep_c_cpt_freq[order(-hep_c_cpt_freq$Freq),], n=10)


#Non Hep C Patients - Number of cpt codes and Average number of cpt codesper patient
non_hep_c_patient_cpt <- cpt[!cpt$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
nrow(non_hep_c_patient_cpt)
nrow(non_hep_c_patient_cpt) / nrow(cpt)
nrow(non_hep_c_patient_cpt)/length(unique(non_hep_c_patient_cpt$PATIENT_ID))

##Frequency of ICD Diagnosis codes
#all records
non_hep_c_cpt_freq<- (as.data.frame(table(non_hep_c_patient_cpt$CPT)))
head(non_hep_c_cpt_freq[order(-non_hep_c_cpt_freq$Freq),], n=10)
```

```{r}
############Examaining data shifting###########

#reduce to date columns only on Encounter table and remove rows without an Encounter ID

names(encounters)

encounter_dates <- encounters [,c("ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "Enc_DT_DS", "Appt_DTTM_DS", "Hsp_Adm_DTTM_DS")]

dim(encounter_dates)



#Reduce ICD Diagnosis table to encounter id and date field only
#merge with encounter table
#Evalute dates
diagnosis_icd_dates <- diagnosis_icd [,c("ENCOUNTER_ID", "enc_dt_ds")]
sum(is.na(diagnosis_icd_dates$ENCOUNTER_ID))
dim(diagnosis_icd_dates)

encounter_icd_diagnosis_date_merge <- merge(encounter_dates, diagnosis_icd_dates, by = "ENCOUNTER_ID", all.x = FALSE, all.y = FALSE)
dim(encounter_icd_diagnosis_date_merge)

encounter_icd_diagnosis_date_merge$date_evaluation <- encounter_icd_diagnosis_date_merge$enc_dt_ds == encounter_icd_diagnosis_date_merge$Enc_DT_DS

encounter_icd_diagnosis_date_merge$date_difference <- difftime(encounter_icd_diagnosis_date_merge$enc_dt_ds, encounter_icd_diagnosis_date_merge$Enc_DT_DS, units = "days")

mean(encounter_icd_diagnosis_date_merge$date_difference, rm.na = TRUE)
icd_diagnosis_false <- subset(encounter_icd_diagnosis_date_merge, date_evaluation == "FALSE")
mean(icd_diagnosis_false$date_difference, rm.na = TRUE)
#Match Rate
nrow(subset(encounter_icd_diagnosis_date_merge, date_evaluation == "TRUE")) / nrow(encounter_icd_diagnosis_date_merge)

subset(diagnosis_icd_dates, ENCOUNTER_ID == "0001945298")
subset(encounter_dates, ENCOUNTER_ID == "0006527994")

###CPT
#Reduce cpt table to encounter id and date field only
#merge with encounter table
#Evalute dates
cpt_dates <- cpt [,c("ENCOUNTER_ID", "enc_dt_ds")]
sum(is.na(cpt_dates$ENCOUNTER_ID))
dim(cpt_dates)

encounter_cpt_date_merge <- merge(encounter_dates, cpt_dates, by = "ENCOUNTER_ID", all.x = FALSE, all.y = FALSE)
dim(encounter_cpt_date_merge)

encounter_cpt_date_merge$date_evaluation <- encounter_cpt_date_merge$enc_dt_ds == encounter_cpt_date_merge$Enc_DT_DS

encounter_cpt_date_merge$date_difference <- difftime(encounter_cpt_date_merge$enc_dt_ds, encounter_cpt_date_merge$Enc_DT_DS, units = "days")

mean(encounter_cpt_date_merge$date_difference, rm.na = TRUE)
subset(encounter_cpt_date_merge, date_evaluation == "FALSE")
#Match Rate
nrow(subset(encounter_cpt_date_merge, date_evaluation == "TRUE")) / nrow(encounter_cpt_date_merge)



###Meds Outpatient
#Reduce meds outpatient table to encounter id and date field only
#merge with encounter table
#Evalute dates

meds_outpt_dates <- meds_outpt [,c("ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "Enc_DT_DS", "Order_DT_DS")]

encounter_meds_outpt_date_merge <- merge(encounter_dates, meds_outpt_dates, by = "PAT_ENC_CSN_ID_DID")
dim(encounter_meds_outpt_date_merge)
names(encounter_meds_outpt_date_merge)

encounter_meds_outpt_date_merge$date_evaluation <- encounter_meds_outpt_date_merge$Enc_DT_DS.x == encounter_meds_outpt_date_merge$Enc_DT_DS.y

encounter_meds_outpt_date_merge$encounter_date_difference <- difftime(encounter_meds_outpt_date_merge$Enc_DT_DS.x, encounter_meds_outpt_date_merge$Enc_DT_DS.y, units = "days")

encounter_meds_outpt_date_merge$order_date_difference <- difftime(encounter_meds_outpt_date_merge$Enc_DT_DS.x, encounter_meds_outpt_date_merge$Order_DT_DS, units = "days")

mean(encounter_meds_outpt_date_merge$encounter_date_difference, rm.na = TRUE)
subset(encounter_meds_outpt_date_merge, date_evaluation == "FALSE")
#Match Rate
nrow(subset(encounter_meds_outpt_date_merge, date_evaluation == "TRUE")) / nrow(encounter_meds_outpt_date_merge)


###Meds Inpatient
#Reduce meds inpatient table to encounter id and date field only
#merge with encounter table
#Evalute dates
meds_inpt_dates <- meds_inpt [,c("ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "HSP_ADM_DTTM_DS", "HSP_Disch_DTTM_DS", "Order_DT_DS")]

encounter_meds_inpt_date_merge <- merge(encounter_dates, meds_inpt_dates, by ="PAT_ENC_CSN_ID_DID")

dim(encounter_meds_inpt_date_merge)
dim(encounter_dates)
dim(meds_inpt_dates)

encounter_meds_inpt_date_merge$date_evaluation <- encounter_meds_inpt_date_merge$Enc_DT_DS == encounter_meds_inpt_date_merge$HSP_ADM_DTTM_DS

encounter_meds_inpt_date_merge$encounter_date_difference <- difftime(encounter_meds_inpt_date_merge$Enc_DT_DS, encounter_meds_inpt_date_merge$HSP_ADM_DTTM_DS, units = "days")
encounter_meds_inpt_date_merge$admit_date_difference <- difftime(encounter_meds_inpt_date_merge$Hsp_Adm_DTTM_DS, encounter_meds_inpt_date_merge$HSP_ADM_DTTM_DS, units = "days")

mean(encounter_meds_inpt_date_merge$admit_date_difference, rm.na = TRUE)
mean(encounter_meds_inpt_date_merge$encounter_date_difference, rm.na = TRUE)
subset(encounter_meds_inpt_date_merge, date_evaluation == "FALSE")

#Match Rate
nrow(subset(encounter_meds_inpt_date_merge, date_evaluation == "TRUE")) / nrow(encounter_meds_inpt_date_merge)

#Procedure ICD
#Reduce procedure icd table to encounter id and date field only
#merge with encounter table
#Evalute dates
procedure_icd_dates <- procedure_icd [,c("ENCOUNTER_ID", "enc_dt_ds")]
encounter_procedure_icd_date_merge <- merge(encounter_dates, procedure_icd_dates, by.x = "ENCOUNTER_ID", all.x = FALSE, all.y = FALSE)
dim(encounter_procedure_icd_date_merge)

encounter_procedure_icd_date_merge$date_evaluation <- encounter_procedure_icd_date_merge$Enc_DT_DS == encounter_procedure_icd_date_merge$Enc_DT_DS

encounter_procedure_icd_date_merge$date_difference <- difftime(encounter_procedure_icd_date_merge$enc_dt_ds, encounter_procedure_icd_date_merge$Enc_DT_DS, units = "days")

mean(encounter_procedure_icd_date_merge$date_difference, rm.na = TRUE)
subset(encounter_procedure_icd_date_merge, date_evaluation == "FALSE")
nrow(subset(encounter_procedure_icd_date_merge, date_evaluation == "TRUE")) / nrow(encounter_procedure_icd_date_merge)



#Social
#Reduce social table to encounter id and date field only
#merge with encounter table
#Evalute dates
social_hx_dates <- social_hx [,c("ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "Enc_DT_DS")]

encounter_social_hx_date_merge <- merge(encounter_dates, social_hx_dates, by ="PAT_ENC_CSN_ID_DID")
dim(social_hx_dates)
dim(encounter_dates)
dim(encounter_social_hx_date_merge)


encounter_social_hx_date_merge$date_evaluation <- encounter_social_hx_date_merge$Enc_DT_DS.x == encounter_social_hx_date_merge$Enc_DT_DS.y

encounter_social_hx_date_merge$date_difference <- difftime(encounter_social_hx_date_merge$Enc_DT_DS.x, encounter_social_hx_date_merge$Enc_DT_DS.y, units = "days")

mean(encounter_social_hx_date_merge$date_difference, rm.na = TRUE)
social_hx_false <- subset(encounter_social_hx_date_merge, date_evaluation == "FALSE")
mean(social_hx_false$date_difference)
#Match Rate
nrow(subset(encounter_social_hx_date_merge, date_evaluation == "TRUE")) / nrow(encounter_social_hx_date_merge)

```

```{r}

########Exploring Demo Table ##########

patient_ID_demo <- as.data.frame(table(demo$PATIENT_ID))
colnames(patient_ID_demo) <- c("PATIENT_ID", "Count_Demo")

sapply(demo, function(x) sum(is.na(x)))

demo$NumMissing = rowSums(is.na(demo))

################Demo data for Hep C patients only##############

demo_hep_c_patients <- subset(demo, PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID) #3785 rows

#remove duplicated rows
demo_hep_c_patients <- demo_hep_c_patients[!duplicated(demo_hep_c_patients),] #3785 rows

demo_hep_c_patients[order(demo_hep_c_patients$PATIENT_ID),]

#find hep c patients listed with demographic data more than once
demo_hep_c_patients[duplicated(demo_hep_c_patients$PATIENT_ID),]#0 ids

demo_freq <- as.data.frame(table(demo_hep_c_patients$PATIENT_ID))#3785 unique id's


demo_hep_c_patients <- merge(demo_hep_c_patients, education, by = "PATIENT_ID", all.x = TRUE, all.y = FALSE)

sum(is.na(demo_hep_c_patients$YEARS_EDUCATION))#2883 missing

table(demo_hep_c_patients$Race)
table(demo_hep_c_patients$Ethnicity)
table(demo_hep_c_patients$language)
table(demo_hep_c_patients$Marital_Status)
sum(!is.na(demo_hep_c_patients$DOD_DS))#408 have died
table(demo_hep_c_patients$YEARS_EDUCATION)
```

```{r}
##########Zip Codes of Hep C patients#############

hep_c_patients_zip_code <- hep_c_patient_encounters[c("Patient_ID", "Encounter_ID", "Pat_Enc_Csn_ID_DID", "Enc_DT_DS", "Zip_Code_DID")]
dim(hep_c_patients_zip_code)


hep_c_patients_zip_code_freq <- as.data.frame(table(hep_c_patients_zip_code$Patient_ID))
colnames(hep_c_patients_zip_code_freq) <- c("Patient_ID", "Count_Zip_Code")
hep_c_patients_zip_code_freq[order(-hep_c_patients_zip_code_freq$Count_Zip_Code),]

```




```{r}
######ENCOUNTERS TABLE######

####Explore data

str(encounters)
tail(encounters)
dim(encounters)

#Patient_ID
summary(encounters$Patient_ID_fac)
sum(is.na(encounters$Patient_ID))

#Encounter_ID
sum(is.na(encounters$Encounter_ID))

#Pat_Enc_Csn_ID_DID
sum(is.na(encounters$Pat_Enc_Csn_ID_DID))

#Zip_Code_DID
sum(is.na(encounters$Zip_Code_DID))

#ENC_AGE
sum(is.na(encounters$ENC_AGE))

#Enc_EIO
sum(is.na(encounters$Enc_EIO))

#Enc_Type_c
sum(is.na(encounters$Enc_Type_c))

#Encounter_Type
sum(is.na(encounters$Encounter_Type))

#Fin_Class_C
sum(is.na(encounters$Fin_Class_C))

#Fin_Class
sum(is.na(encounters$Fin_Class))

#PCP_Prov_ID
sum(is.na(encounters$PCP_Prov_ID))

#PCP_Resource
sum(is.na(encounters$PCP_Resource))

#PCP_Prov_Service_C
sum(is.na(encounters$PCP_Prov_Service_C))

#PCP_Prov_Service
sum(is.na(encounters$PCP_Prov_Service))

#Enc_DT_DS
sum(is.na(encounters$Enc_DT_DS))

#Appt_DTTM_DS
sum(is.na(encounters$Appt_DTTM_DS))

#Appt_Checkin_DTTM
sum(is.na(encounters$Appt_Checkin_DTTM))

#Appt_Status_C
sum(is.na(encounters$Appt_Status_C))

#Appt_Status
sum(is.na(encounters$Appt_Status))

#Appt_Cancel_DTTM_DS
sum(is.na(encounters$Appt_Cancel_DTTM_DS))

#Appt_Primary_Loc_ID
sum(is.na(encounters$Appt_Primary_Loc_ID))

#Appt_Primary_Location
sum(is.na(encounters$Appt_Primary_Location))

#Appt_Dept_ID
sum(is.na(encounters$Appt_Dept_ID))

#Appt_Dept
sum(is.na(encounters$Appt_Dept))

#Appt_Prov_ID
sum(is.na(encounters$Appt_Prov_ID))

#Appt_Resource
sum(is.na(encounters$Appt_Resource))

#Appt_Prov_Service_C
sum(is.na(encounters$Appt_Prov_Service_C))

#Appt_Prov_Service
sum(is.na(encounters$Appt_Prov_Service))

#ED_Arrival_DTTM_DS
sum(is.na(encounters$ED_Arrival_DTTM_DS))

#ED_Disposition_C
sum(is.na(encounters$ED_Disposition_C))

#ED_Disposition
sum(is.na(encounters$ED_Disposition))

#Hsp_Adm_DTTM_DS
sum(is.na(encounters$Hsp_Adm_DTTM_DS))

#Hsp_Disch_DTTM_DS
sum(is.na(encounters$Hsp_Disch_DTTM_DS))

#LOS_Days
sum(is.na(encounters$LOS_Days))

#LOS_Hrs
sum(is.na(encounters$LOS_Hrs))

#Means_of_Arrival_C
sum(is.na(encounters$Means_of_Arrival_C))

#Means_of_Arrival
sum(is.na(encounters$Means_of_Arrival))

#Admit_Source_C
sum(is.na(encounters$Admit_Source_C))

#Admit_Source
sum(is.na(encounters$Admit_Source))

#First_Enc_Dept
sum(is.na(encounters$First_Enc_Dept))

#First_Enc_Service
sum(is.na(encounters$First_Enc_Service))

#First_Prov_ID
sum(is.na(encounters$First_Prov_ID))

#First_Resource
sum(is.na(encounters$First_Resource))

#First_Prov_Specialty_C
sum(is.na(encounters$First_Prov_Specialty_C))

#First_Prov_Specialty
sum(is.na(encounters$First_Prov_Specialty))

#Center_C
sum(is.na(encounters$Center_C))

#Center
sum(is.na(encounters$Center))

#Room
sum(is.na(encounters$Room))

#Last_Enc_Dept
sum(is.na(encounters$Last_Enc_Dept))

#Last_Enc_Service
sum(is.na(encounters$Last_Enc_Service))

#Last_Prov_ID
sum(is.na(encounters$Last_Prov_ID))

#Last_Resource
sum(is.na(encounters$Last_Resource))

#Last_Prov_Specialty_C
sum(is.na(encounters$Last_Prov_Specialty_C))

#Last_Prov_Specialty
sum(is.na(encounters$Last_Prov_Specialty))

#Disch_Dispo_C
sum(is.na(encounters$Disch_Dispo_C))

#Disch_Dispo
sum(is.na(encounters$Disch_Dispo))

#Pt_Encs
sum(is.na(encounters$Pt_Encs))

#Service_Area_C
sum(is.na(encounters$Service_Area_C))

#Service_Area
sum(is.na(encounters$Service_Area))

```




```{r cars}
########CPT File##########

str(cpt)
head(cpt)
dim(cpt)

#Patient ID
length(unique(cpt$patient_id))
sum(is.na(cpt$patient_id))

##Match CPT codes per Dr Davis's email
hep_c_cpt <- subset(cpt, 
                        CPT == "86803" | #Hep C antibody
                        CPT == "86804" | #Hep C antibody, confirmatory test
                        CPT == "87520" | #Hep C direct probe technique
                        CPT == "87521" | #Hep C amplified probe technique
                        CPT == "87522"  #Hep C quantification
                      )

dim(hep_c_cpt)#576 rows



```


```{r}
##########Med_Rec_Adm File########

str(med_rec_adm)
dim(med_rec_adm)
head(med_rec_adm)
names(med_rec_adm)

#Patient ID
length(unique(med_rec_adm$PATIENT_ID))
sum(is.na(med_rec_adm$PATIENT_ID))

#Encounter ID
length(unique(med_rec_adm$ENCOUNTER_ID))
sum(is.na(med_rec_adm$ENCOUNTER_ID)) 

#Serial # for ethe patient contact
length(unique(med_rec_adm$PAT_ENC_CSN_ID_DID))
sum(is.na(med_rec_adm$PAT_ENC_CSN_ID_DID)) 

#Billing type of encouter
table(med_rec_adm$Enc_EIO)
sum(is.na(med_rec_adm$Enc_EIO))

#Encounter category type - integar
table(med_rec_adm$ENC_TYPE_C) 
sum(is.na(med_rec_adm$ENC_TYPE_C))

#Encounter Type - descriptive
med_rec_adm$ENCOUNTER_TYPE
table(med_rec_adm$ENCOUNTER_TYPE) 
sum(is.na(med_rec_adm$ENCOUNTER_TYPE))

#Hospital admission date and time
med_rec_adm$Hsp_Adm_DTTM_DS
sum(is.na(med_rec_adm$Hsp_Adm_DTTM_DS))

#Hospital discharge date and time
med_rec_adm$Hsp_Disch_DTTM_DS
sum(is.na(med_rec_adm$Hsp_Disch_DTTM_DS))

#Code for location of medication reconciliation
med_rec_adm$ADMIT_DEPT_ID
dim(table(med_rec_adm$ADMIT_DEPT_ID))
sum(is.na(med_rec_adm$ADMIT_DEPT_ID))

#Location of med reconciliation - descricption
med_rec_adm$ADMIT_DEPT
table(med_rec_adm$ADMIT_DEPT) 
sum(is.na(med_rec_adm$ADMIT_DEPT))

#Code for service providering care for patient
med_rec_adm$ADMIT_SERV_C
table(med_rec_adm$ADMIT_SERV_C)
sum(is.na(med_rec_adm$ADMIT_SERV_C))

#Service providing care for patient - descirptive
med_rec_adm$ADMIT_SERVICE_AREA
dim(table(med_rec_adm$ADMIT_SERVICE_AREA))
sum(is.na(med_rec_adm$ADMIT_SERVICE_AREA))

#Code for medication confirmed with patient upon admission or discharge
med_rec_adm$MED_REC_EVENT_C
table(med_rec_adm$MED_REC_EVENT_C)
sum(is.na(med_rec_adm$MED_REC_EVENT_C))

#medication confirmed with patient upon admit or discharge - descriptive
med_rec_adm$MED_REC_EVENT
table(med_rec_adm$MED_REC_EVENT)
sum(is.na(med_rec_adm$MED_REC_EVENT))

#was patient inpatient or outpatient - all outpatient
med_rec_adm$MED_ORDERING_MODE
table(med_rec_adm$MED_ORDERING_MODE)
sum(is.na(med_rec_adm$MED_ORDERING_MODE))

#Date med was ordered
med_rec_adm$MED_ORDER_DTTM_DS
sum(is.na(med_rec_adm$MED_ORDER_DTTM_DS))

#date med was discontinued
med_rec_adm$MED_DC_DTTM_DS
sum(is.na(med_rec_adm$MED_DC_DTTM_DS))

#date med was reconciled
med_rec_adm$MED_REC_DTTM_DS
sum(is.na(med_rec_adm$MED_REC_DTTM_DS))

#All values are the same - 35000
med_rec_adm$MED_REC_TYPE_C
table(med_rec_adm$MED_REC_TYPE_C)
sum(is.na(med_rec_adm$MED_REC_TYPE_C))

#all values are the same - "IP Admission Reconciliation""
med_rec_adm$MED_REC_TYPE
table(med_rec_adm$MED_REC_TYPE)
sum(is.na(med_rec_adm$MED_REC_TYPE))

#Code for determined status of meds during reconciliation
med_rec_adm$MED_REC_ACTION_C
table(med_rec_adm$MED_REC_ACTION_C)
sum(is.na(med_rec_adm$MED_REC_ACTION_C))

#Determined status of meds during reconciliation - descriptive
med_rec_adm$MED_REC_ACTION
table(med_rec_adm$MED_REC_ACTION)
sum(is.na(med_rec_adm$MED_REC_ACTION))
   
# "RSN_FOR_DISCON_C"   "RSN_FOR_DISCON_MED"
med_rec_adm$RSN_FOR_DISCON_C
table(med_rec_adm$RSN_FOR_DISCON_C)
sum(is.na(med_rec_adm$RSN_FOR_DISCON_C))

med_rec_adm$RSN_FOR_DISCON_MED
table(med_rec_adm$RSN_FOR_DISCON_MED)
sum(is.na(med_rec_adm$RSN_FOR_DISCON_MED))

#[25] "MEDICATION_ID"      "MEDICATION"   

med_rec_adm$MEDICATION_ID
length(unique(med_rec_adm$MEDICATION_ID))
sum(is.na(med_rec_adm$MEDICATION_ID))

med_rec_adm$MEDICATION
length(unique(med_rec_adm$MEDICATION))
sum(is.na(med_rec_adm$MEDICATION))


med_rec_adm$ORDER_MED_DOSE
length(unique(med_rec_adm$ORDER_MED_DOSE))
sum(is.na(med_rec_adm$ORDER_MED_DOSE))

#how med was administered - IV, topical, oral
med_rec_adm$MED_ROUTE
table(med_rec_adm$MED_ROUTE)
sum(is.na(med_rec_adm$MED_ROUTE))

#How often the med needs to be taken
med_rec_adm$ORDER_MED_FREQ
dim(table(med_rec_adm$ORDER_MED_FREQ))
sum(is.na(med_rec_adm$ORDER_MED_FREQ))

#Code for Therapeutic status
med_rec_adm$THERA_CLASS_C
dim(table(med_rec_adm$THERA_CLASS_C))
sum(is.na(med_rec_adm$THERA_CLASS_C))

#Descriptive for Therapeutic status
med_rec_adm$THERA_CLASS
dim(table(med_rec_adm$THERA_CLASS))
sum(is.na(med_rec_adm$THERA_CLASS))

#Code for Pharmaceutical class
med_rec_adm$PHARM_CLASS_C
dim(table(med_rec_adm$PHARM_CLASS_C))
sum(is.na(med_rec_adm$PHARM_CLASS_C))

#Descriptive for Pharmaceutical class
med_rec_adm$PHARM_CLASS
dim(table(med_rec_adm$PHARM_CLASS))
sum(is.na(med_rec_adm$PHARM_CLASS))


#Code for pharmaceutical sub class name
med_rec_adm$PHARM_SUBCLASS_C
dim(table(med_rec_adm$PHARM_SUBCLASS_C))
sum(is.na(med_rec_adm$PHARM_SUBCLASS_C))

#Descriptive for pharmaceutical sub class name
med_rec_adm$PHARM_SUB_CLASS
dim(table(med_rec_adm$PHARM_SUB_CLASS))
sum(is.na(med_rec_adm$PHARM_SUB_CLASS))

med_rec_adm$EVENT_MED_REC_LINE
dim(table(med_rec_adm$EVENT_MED_REC_LINE))
sum(is.na(med_rec_adm$EVENT_MED_REC_LINE))


anti_viral_med_rec_adm <- subset(med_rec_adm, THERA_CLASS == "ANTIVIRALS")

dim(anti_viral_med_rec_adm)#1296



```


```{r}
##########Med_Rec_Dc File########


#### explore data
str(med_rec_dc)
head(med_rec_dc)
names(med_rec_dc)
dim(med_rec_dc)

#Patient ID's
length(unique(med_rec_dc$PATIENT_ID))
sum(is.na(med_rec_dc$PATIENT_ID))

#Encournter ID
length(unique(med_rec_dc$ENCOUNTER_ID))
sum(is.na(med_rec_dc$ENCOUNTER_ID)) 

# serial # of patient contact
length(unique(med_rec_dc$PAT_ENC_CSN_ID_DID))
sum(is.na(med_rec_dc$PAT_ENC_CSN_ID_DID)) 

#encounter Type
table(med_rec_dc$ENC_TYPE_C) 
sum(is.na(med_rec_dc$ENC_TYPE_C))

med_rec_dc$ENC_TYPE
table(med_rec_dc$ENC_TYPE) 
sum(is.na(med_rec_dc$ENC_TYPE))

#Encounter Type
table(med_rec_dc$Enc_eio)
sum(is.na(med_rec_dc$Enc_eio))


#hopital admission date and time for 
med_rec_dc$Hsp_Adm_DTTM_DS
sum(is.na(med_rec_dc$Hsp_Adm_DTTM_DS))

#hopital discharge date and time
med_rec_dc$Hsp_Disch_DTTM_DS
sum(is.na(med_rec_dc$Hsp_Disch_DTTM_DS))

#location of medication reconciliation
med_rec_dc$DC_DEPT_ID
dim(table(med_rec_dc$DC_DEPT_ID))
table(med_rec_dc$DC_DEPT_ID)
sum(is.na(med_rec_dc$DC_DEPT_ID))

#location of med reconciliation = descriptive
med_rec_dc$DC_DEPT
table(med_rec_dc$DC_DEPT) 
sum(is.na(med_rec_dc$DC_DEPT))

#service line providing care for patient
med_rec_dc$DC_SERV_C
table(med_rec_dc$DC_SERV_C)
sum(is.na(med_rec_dc$DC_SERV_C))

#service line providing care for patients - descriptive
med_rec_dc$DC_SERVICE_AREA
dim(table(med_rec_dc$DC_SERVICE_AREA))
table(med_rec_dc$DC_SERVICE_AREA)
sum(is.na(med_rec_dc$DC_SERVICE_AREA))

#medication confirmed upon discharge - all same value
med_rec_dc$ADT_DC_EVENT_C
table(med_rec_dc$ADT_DC_EVENT_C)
sum(is.na(med_rec_dc$ADT_DC_EVENT_C))

#medication confirmed upon discharge - all same value
med_rec_dc$ADT_DC_EVENT
table(med_rec_dc$ADT_DC_EVENT)
sum(is.na(med_rec_dc$ADT_DC_EVENT))

#
med_rec_dc$DC_DISP_C
table(med_rec_dc$DC_DISP_C)
sum(is.na(med_rec_dc$DC_DISP_C))

#Disposition
med_rec_dc$DC_DISPOSITION
table(med_rec_dc$DC_DISPOSITION)
sum(is.na(med_rec_dc$DC_DISPOSITION))

#Med confirmed with patient upon discharge
med_rec_dc$MED_REC_EVENT_C
table(med_rec_dc$MED_REC_EVENT_C)
sum(is.na(med_rec_dc$MED_REC_EVENT_C))

#medication confirmed with patient upon discharge - all same value
med_rec_dc$MED_REC_EVENT
table(med_rec_dc$MED_REC_EVENT)
sum(is.na(med_rec_dc$MED_REC_EVENT))

#where medication ordered
med_rec_dc$MED_ORDERING_MODE
table(med_rec_dc$MED_ORDERING_MODE)
sum(is.na(med_rec_dc$MED_ORDERING_MODE))


med_rec_dc$MED_ORDER_DTTM_DS
sum(is.na(med_rec_dc$MED_ORDER_DTTM_DS))

med_rec_dc$MED_DC_DTTM_DS
sum(is.na(med_rec_dc$MED_DC_DTTM_DS))

med_rec_dc$MED_REC_DTTM_DS
sum(is.na(med_rec_dc$MED_REC_DTTM_DS))


med_rec_dc$MED_REC_TYPE_C
table(med_rec_dc$MED_REC_TYPE_C)
sum(is.na(med_rec_dc$MED_REC_TYPE_C))

#all values are the same but 1 is blank = "IP Discharge Reconciltion"
med_rec_dc$MED_REC_TYPE
table(med_rec_dc$MED_REC_TYPE)
sum(is.na(med_rec_dc$MED_REC_TYPE))

#determined status of medication during reconciliation
med_rec_dc$MED_REC_ACTION_C
table(med_rec_dc$MED_REC_ACTION_C)
sum(is.na(med_rec_dc$MED_REC_ACTION_C))

#determined status of medication during reconciliation - desciptive
med_rec_dc$MED_REC_ACTION
table(med_rec_dc$MED_REC_ACTION)
sum(is.na(med_rec_dc$MED_REC_ACTION))
   
# "RSN_FOR_DISCON_C"   "RSN_FOR_DISCON_MED"
med_rec_dc$RSN_FOR_DISCON_C
table(med_rec_dc$RSN_FOR_DISCON_C)
sum(is.na(med_rec_dc$RSN_FOR_DISCON_C))

med_rec_dc$RSN_FOR_DISCON_MED
table(med_rec_dc$RSN_FOR_DISCON_MED)
sum(is.na(med_rec_dc$RSN_FOR_DISCON_MED))

#"MEDICATION_ID"        

med_rec_dc$MEDICATION_ID
table(med_rec_dc$MEDICATION_ID)
dim(table(med_rec_dc$MEDICATION_ID))
sum(is.na(med_rec_dc$MEDICATION_ID))


#"MEDICATION" 
med_rec_dc$MEDICATION
table(med_rec_dc$MEDICATION)
dim(table(med_rec_dc$MEDICATION))
sum(is.na(med_rec_dc$MEDICATION))


#dosage of meds
med_rec_dc$ORDER_MED_DOSE
length(unique(med_rec_dc$ORDER_MED_DOSE))
sum(is.na(med_rec_dc$ORDER_MED_DOSE))

#how the med was administered
med_rec_dc$MED_ROUTE
table(med_rec_dc$MED_ROUTE)
dim(table(med_rec_dc$MED_ROUTE))
sum(is.na(med_rec_dc$MED_ROUTE))


#frequency of dosage
med_rec_dc$ORDER_MED_FREQ
dim(table(med_rec_dc$ORDER_MED_FREQ))
sum(is.na(med_rec_dc$ORDER_MED_FREQ))


med_rec_dc$THERA_CLASS_C
dim(table(med_rec_dc$THERA_CLASS_C))
sum(is.na(med_rec_dc$THERA_CLASS_C))

med_rec_dc$PHARM_CLASS_C
dim(table(med_rec_dc$PHARM_CLASS_C))
sum(is.na(med_rec_dc$PHARM_CLASS_C))

med_rec_dc$MED_PHARM_CLASS
dim(table(med_rec_dc$MED_PHARM_CLASS))
sum(is.na(med_rec_dc$MED_PHARM_CLASS))

med_rec_dc$PHARM_SUBCLASS_C
dim(table(med_rec_dc$PHARM_SUBCLASS_C))
sum(is.na(med_rec_dc$PHARM_SUBCLASS_C))

med_rec_dc$PHARM_SUB_CLASS
dim(table(med_rec_dc$PHARM_SUB_CLASS))
sum(is.na(med_rec_dc$PHARM_SUB_CLASS))

med_rec_dc$EVENT_MED_REC_LINE
dim(table(med_rec_dc$EVENT_MED_REC_LINE))
sum(is.na(med_rec_dc$EVENT_MED_REC_LINE))

```



```{r}
##########Meds_Inpt File########

str(meds_inpt)
head(meds_inpt)
dim(meds_inpt)


#Patient_ID and extract to CSV
sum(is.na(meds_inpt$Patient_ID))
write.table(meds_inpt$Patient_ID, file = paste("C:/Users/laura.olson/",'meds_inpt_Patient_ID.csv',sep = '/'), row.names = F) #save all Patient IDs as CSV

#Encounter_ID
sum(is.na(meds_inpt$Encounter_ID))

#Pat_Enc_Csn_ID_DID
sum(is.na(meds_inpt$Pat_Enc_Csn_ID_DID))

#HSP_ADM_DTTM_DS
sum(is.na(meds_inpt$HSP_ADM_DTTM_DS))

#HSP_Disch_DTTM_DS
sum(is.na(meds_inpt$HSP_Disch_DTTM_DS))

#Med_Dept
sum(is.na(meds_inpt$Med_Dept))

#Order_DT_DS
sum(is.na(meds_inpt$Order_DT_DS))

#Thera_class_c
sum(is.na(meds_inpt$Thera_class_c))

#Thera_class
sum(is.na(meds_inpt$Thera_class))

#Pharm_class_c
sum(is.na(meds_inpt$Pharm_class_c))

#Pharm_class
sum(is.na(meds_inpt$Pharm_class))

#Pharm_subclass_c
sum(is.na(meds_inpt$Pharm_subclass_c))

#Pharm_subclass
sum(is.na(meds_inpt$Pharm_subclass))

#Medication_id
sum(is.na(meds_inpt$Medication_id))

#Medication_id
sum(is.na(meds_inpt$Medication))

#GPI
sum(is.na(meds_inpt$GPI))

#Generic_name
sum(is.na(meds_inpt$Generic_name))

#Order_Med_Dose
sum(is.na(meds_inpt$Order_Med_Dose))

#Med_Route
sum(is.na(meds_inpt$Med_Route))

#Order_Med_Freq
sum(is.na(meds_inpt$Order_Med_Freq))

#Order_Start_DTTM_DS
sum(is.na(meds_inpt$Order_Start_DTTM_DS))

#Order_End_DTTM_DS
sum(is.na(meds_inpt$Order_End_DTTM_DS))

#MAR_Dose
sum(is.na(meds_inpt$MAR_Dose))

#MAR_Gave_DTTM_DS
sum(is.na(meds_inpt$MED_Gave_DTTM_DS))

#MAR_Sched_DTTM_DS
sum(is.na(meds_inpt$MED_Sched_DTTM_DS))

#MAR_Action
sum(is.na(meds_inpt$MAR_Action))

#Ordering_Mode
sum(is.na(meds_inpt$Ordering_Mode))

#Check cleaned data
str(meds_inpt)


```


```{r}
##########Meds_Outpt File########

str(meds_outpt)
head(meds_outpt)
dim(meds_outpt)

#Patient_ID
sum(is.na(meds_outpt$Patient_ID))

#Encounter_ID
sum(is.na(meds_outpt$Encounter_ID))

#Pat_Enc_Csn_ID_DID
sum(is.na(meds_outpt$Pat_Enc_Csn_ID_DID))

#Pat_Enc_DT_DS
sum(is.na(meds_outpt$Enc_DT_DS))

#Med_Dept
sum(is.na(meds_outpt$Med_Dept))

#Order_DT_DS
sum(is.na(meds_outpt$Order_DT_DS))

#Thera_class_c
sum(is.na(meds_outpt$Thera_class_c))

#Thera_class
sum(is.na(meds_outpt$Thera_class))

#Pharm_class_c
sum(is.na(meds_outpt$Pharm_class_c))

#Pharm_class
sum(is.na(meds_outpt$Pharm_class))

#Pharm_subclass_c
sum(is.na(meds_outpt$Pharm_subclass_c))

#Pharm_subclass
sum(is.na(meds_outpt$Pharm_subclass))

#Medication_id
sum(is.na(meds_outpt$Medication_id))

#Medication_id
sum(is.na(meds_outpt$Medication))

#GPI
sum(is.na(meds_outpt$GPI))

#Generic_name
sum(is.na(meds_outpt$Generic_name))

#SIG
sum(is.na(meds_outpt$SIG))

#QUANTITY
sum(is.na(meds_outpt$QUANTITY))

#REFILLS
sum(is.na(meds_outpt$REFILLS))

#Order_Med_Dose
sum(is.na(meds_outpt$Order_Med_Dose))

#Med_Route
sum(is.na(meds_outpt$Med_Route))

#Order_Med_Freq
sum(is.na(meds_outpt$Order_Med_Freq))

#Order_Start_DTTM_DS
sum(is.na(meds_outpt$Order_Start_DTTM_DS))

#Order_End_DTTM_DS
sum(is.na(meds_outpt$Order_End_DTTM_DS))

#Ordering_Mode
sum(is.na(meds_outpt$Ordering_Mode))

```


```{r}
##########Procedure_ICD File########

str(procedure_icd)
head(procedure_icd)
dim(procedure_icd)

```


```{r}
##########Social_Hx File########
str(social_hx)
head(social_hx)
dim(social_hx)
names(social_hx)

social_hx$Patient_ID
sum(is.na(social_hx$Patient_ID))

social_hx$Encounter_ID
sum(is.na(social_hx$Encounter_ID))

social_hx$Pat_Enc_Csn_ID_DID
sum(is.na(social_hx$Pat_Enc_Csn_ID_DID))

social_hx$Enc_DT_DS
sum(is.na(social_hx$Enc_DT_DS))

social_hx$Hx_SOURCE_C
sum(is.na(social_hx$Hx_SOURCE_C))
table(social_hx$Hx_SOURCE_C)

social_hx$Hx_SOURCE
sum(is.na(social_hx$Hx_SOURCE))
table(social_hx$Hx_SOURCE)

#Tobacco Use Status
social_hx$TOBACCO_USER_C
sum(is.na(social_hx$TOBACCO_USER_C))
table(social_hx$TOBACCO_USER_C)

social_hx$TOBACCO_USER
sum(is.na(social_hx$TOBACCO_USER))
table(social_hx$TOBACCO_USER)

social_hx$SMOKING_TOB_USE_C
sum(is.na(social_hx$SMOKING_TOB_USE_C))
table(social_hx$SMOKING_TOB_USE_C)

social_hx$SMOKING_TOB_USE
sum(is.na(social_hx$SMOKING_TOB_USE))
table(social_hx$SMOKING_TOB_USE)

social_hx$TOBACCO_PAK_PER_DY
sum(is.na(social_hx$TOBACCO_PAK_PER_DY))
table(social_hx$TOBACCO_PAK_PER_DY)

social_hx$TOBACCO_USED_YEARS
sum(is.na(social_hx$TOBACCO_USED_YEARS))
table(social_hx$TOBACCO_USED_YEARS)

social_hx$TOBACCO_COMMENT
sum(is.na(social_hx$TOBACCO_COMMENT))

social_hx$SMOKING_START_DATE_DS
sum(is.na(social_hx$SMOKING_START_DATE_DS))

social_hx$SMOKING_QUIT_DATE_DS
sum(is.na(social_hx$SMOKING_QUIT_DATE_DS))
     
social_hx$CIGARETTES_YN
sum(is.na(social_hx$CIGARETTES_YN))
table(social_hx$CIGARETTES_YN)

social_hx$PIPES_YN
sum(is.na(social_hx$PIPES_YN))
table(social_hx$PIPES_YN)

social_hx$CIGARS_YN
sum(is.na(social_hx$CIGARS_YN))
table(social_hx$CIGARS_YN)

social_hx$SMOKELESS_TOB_USE_C
sum(is.na(social_hx$SMOKELESS_TOB_USE_C))
table(social_hx$SMOKELESS_TOB_USE_C)

social_hx$SMOKELESS_TOB_USE
sum(is.na(social_hx$SMOKELESS_TOB_USE))
table(social_hx$SMOKELESS_TOB_USE)

social_hx$SNUFF_YN
sum(is.na(social_hx$SNUFF_YN))
table(social_hx$SNUFF_YN)

social_hx$CHEW_YN
sum(is.na(social_hx$CHEW_YN))
table(social_hx$CHEW_YN)

social_hx$SMOKELESS_QUIT_DATE_DS
sum(is.na(social_hx$SMOKELESS_QUIT_DATE_DS))

#Alchol
social_hx$ALCOHOL_USE_C
sum(is.na(social_hx$ALCOHOL_USE_C))
table(social_hx$ALCOHOL_USE_C)

social_hx$ALCOHOL_USE
sum(is.na(social_hx$ALCOHOL_USE))
table(social_hx$ALCOHOL_USE)

social_hx$HX_DRINK_TYPES_C
sum(is.na(social_hx$HX_DRINK_TYPES_C))
table(social_hx$HX_DRINK_TYPES_C)

social_hx$HX_DRINK_TYPES
sum(is.na(social_hx$HX_DRINK_TYPES))
table(social_hx$HX_DRINK_TYPES)

social_hx$ALCOHOL_DRINKS_WK
sum(is.na(social_hx$ALCOHOL_DRINKS_WK))
table(social_hx$ALCOHOL_DRINKS_WK)

social_hx$ALCOHOL_OZ_PER_WK
sum(is.na(social_hx$ALCOHOL_OZ_PER_WK))
table(social_hx$ALCOHOL_OZ_PER_WK)

social_hx$ALCOHOL_COMMENT
sum(is.na(social_hx$ALCOHOL_COMMENT))
table(social_hx$ALCOHOL_COMMENT)

#Drug Use
social_hx$ILL_DRUG_USER_C
sum(is.na(social_hx$ILL_DRUG_USER_C))
table(social_hx$ILL_DRUG_USER_C)

social_hx$ILL_DRUG_USER
sum(is.na(social_hx$ILL_DRUG_USER))
table(social_hx$ILL_DRUG_USER)

social_hx$IV_DRUG_USER_YN
sum(is.na(social_hx$IV_DRUG_USER_YN))
table(social_hx$IV_DRUG_USER_YN)

social_hx$ILLICIT_DRUG_FREQ
sum(is.na(social_hx$ILLICIT_DRUG_FREQ))
table(social_hx$ILLICIT_DRUG_FREQ)

social_hx$ILLICIT_DRUG_CMT
sum(is.na(social_hx$ILLICIT_DRUG_CMT))

#Sexual Activity
social_hx$SEXUALLY_ACTIVE_C
sum(is.na(social_hx$SEXUALLY_ACTIVE_C))
table(social_hx$SEXUALLY_ACTIVE_C)

social_hx$SEXUALLY_ACTIVE
sum(is.na(social_hx$SEXUALLY_ACTIVE))
table(social_hx$SEXUALLY_ACTIVE)

social_hx$FEMALE_PARTNER_YN
sum(is.na(social_hx$FEMALE_PARTNER_YN))
table(social_hx$FEMALE_PARTNER_YN)

social_hx$MALE_PARTNER_YN
sum(is.na(social_hx$MALE_PARTNER_YN))
table(social_hx$MALE_PARTNER_YN)

#Birth Control
social_hx$CONDOM_YN
sum(is.na(social_hx$CONDOM_YN))
table(social_hx$CONDOM_YN)

social_hx$PILL_YN
sum(is.na(social_hx$PILL_YN))
table(social_hx$PILL_YN)

social_hx$DIAPHRAGM_YN
sum(is.na(social_hx$DIAPHRAGM_YN))
table(social_hx$DIAPHRAGM_YN)

social_hx$IUD_YN
sum(is.na(social_hx$IUD_YN))
table(social_hx$IUD_YN)

social_hx$SURGICAL_YN
sum(is.na(social_hx$SURGICAL_YN))
table(social_hx$SURGICAL_YN)

social_hx$SPERMICIDE_YN
sum(is.na(social_hx$SPERMICIDE_YN))
table(social_hx$SPERMICIDE_YN)

social_hx$IMPLANT_YN
sum(is.na(social_hx$IMPLANT_YN))
table(social_hx$IMPLANT_YN)

social_hx$RHYTHM_YN
sum(is.na(social_hx$RHYTHM_YN))
table(social_hx$RHYTHM_YN)

social_hx$INJECTION_YN
sum(is.na(social_hx$INJECTION_YN))
table(social_hx$INJECTION_YN)

social_hx$SPONGE_YN
sum(is.na(social_hx$SPONGE_YN))
table(social_hx$SPONGE_YN)

social_hx$INSERTS_YN
sum(is.na(social_hx$INSERTS_YN))
table(social_hx$INSERTS_YN)

social_hx$ABSTINENCE_YN
sum(is.na(social_hx$ABSTINENCE_YN))
table(social_hx$ABSTINENCE_YN)

social_hx$SEX_COMMENT
sum(is.na(social_hx$SEX_COMMENT))

social_hx$UNKNOWN_FAM_HX_YN
sum(is.na(social_hx$UNKNOWN_FAM_HX_YN))
table(social_hx$UNKNOWN_FAM_HX_YN)

#Employment History
social_hx$OCCUPATION_C
sum(is.na(social_hx$OCCUPATION_C))
table(social_hx$OCCUPATION_C)

social_hx$OCCUPATION
sum(is.na(social_hx$OCCUPATION))
table(social_hx$OCCUPATION)

social_hx$EMPY_STATUS_C
sum(is.na(social_hx$EMPY_STATUS_C))
table(social_hx$EMPY_STATUS_C)

social_hx$EMPLOYMENT_STATUS
sum(is.na(social_hx$EMPLOYMENT_STATUS))
table(social_hx$EMPLOYMENT_STATUS)


```


```{r}
###############Demo File##############
demo<-read_delim("Z:/RAW NEW 3.28.2017/Demo_no_ED_20170329.txt", "|", escape_double = FALSE, trim_ws = TRUE)#Cindy's data path for new demo table

str(demo)
dim(demo)

#patient id
demo$PATIENT_ID
sum(is.na(demo$PATIENT_ID))

#DOB
demo$DOB_DS
sum(is.na(demo$PATIENT_ID))

#Gender
demo$Gender
unique(demo$Gender)
(table(demo$Gender))
sum(is.na(demo$Gender))

#Flag Gender
demo$Flag_Gender
unique(demo$Flag_Gender)
sum(is.na(demo$Flag_Gender))

#Race
demo$Race_Code
unique(demo$Race_Code)
(table(demo$Race_Code))
sum(is.na(demo$Race_Code))

demo$Race
unique(demo$Race)
(table(demo$Race))
sum(is.na(demo$Race))

#Ethnic
demo$Ethnic_Code
unique(demo$Ethnic_Code)
(table(demo$Ethnic_Code))
sum(is.na(demo$Ethnic_Code))

demo$Ethnicity
unique(demo$Ethnicity)
(table(demo$Ethnicity))
sum(is.na(demo$Ethnicity))

#Language
demo$Language_Code
unique(demo$Language_Code)
(table(demo$Language_Code))
sum(is.na(demo$Language_Code))

demo$Language
unique(demo$Language)
dim(table(demo$Language))
sum(is.na(demo$Language))

#Marital_Status
demo$Marital_Status_Code
unique(demo$Marital_Status_Code)
dim(table(demo$Marital_Status_Code))
sum(is.na(demo$Marital_Status_Code))

demo$Marital_Status
unique(demo$Marital_Status)
(table(demo$Marital_Status))
sum(is.na(demo$Marital_Status))

#Date of Death
demo$DOD_DS
sum(is.na(demo$DOD_DS))

```



```{r}
#######Old Code ######

#Match "Hepatitis" to icd description
hep_c_icd_diagnosis_v1 <- diagnosis_icd[grep("HEPATITIS", diagnosis_icd$icd_diagnosis),]#grep search for matches to "Hepatitis within each element of a character vector:
dim(hep_c_icd_diagnosis_v1)#39432 rows
table(hep_c_icd_diagnosis_v1$icd_diagnosis)
length(table(hep_c_icd_diagnosis_v1$icd_diagnosis))

#Barplot
hep_c_icd_diagnosis_v1_graph <- barplot(table(hep_c_icd_diagnosis_v1$icd_dx), 
                                 xlab = "ICD Code", ylab = "Frequency", main = "# of Times ICD Code Appears in ICD Table", cex.names = .5, 
                                 ylim = c(0, 20000))
#text(hep_c_icd_diagnosis_v1_graph, table(hep_c_icd_diagnosis_v1$icd_dx), labels = table(hep_c_icd_diagnosis_v1$icd_dx), cex = .5, pos = 3)

length(unique(hep_c_icd_diagnosis_v1$patient_id)) #6892 unique patient id's
```


```{r}
##Match icd 9 codes that have "Hepatitis C" in the description
hep_c_icd_diagnosis_v2 <- diagnosis_icd[grep("HEPATITIS C", diagnosis_icd$icd_diagnosis),]  #grep search for matches to "Hepatitis C"" within each element of a character vector:
dim(hep_c_icd_diagnosis_v2)#27445 rows
table(hep_c_icd_diagnosis_v2$icd_diagnosis)
length(table(hep_c_icd_diagnosis_v2$icd_diagnosis))
length(unique(hep_c_icd_diagnosis_v2$patient_id))#3322 unique patient id's

unique(hep_c_icd_diagnosis_v2$icd_dx)
unique(hep_c_icd_diagnosis_v2$icd_diagnosis)
```
